name: Hugs
main: com.gmail.nomad856.kamakarzy.Main
version: 1.3

commands:
   hugs:
      description: hug target player
      usage: /hugs <playername>
   kiss:
      description: kiss target player
      usage: /kiss <playername>
   willyoumarryme:
      desscription: ask a player to marry you
      usage: /willyoumarryme <playername>
   ido:
      desscription: accept a players request
      usage: /ido <playername>
   no:
      desscription: decline a players request
      usage: /no